var subject = require('./subject.js')
var mock = require('mock-fs');
var faker = require('faker')
subject.inc('',undefined);
subject.inc('',2);
subject.inc(0,2);
subject.inc(-1,2);
subject.inc(-1,2);
subject.fileTest('path/fileExists','');
subject.fileTest('path/fileExists','path/fileExists');
subject.fileTest('path/fileExists','pathContent/file1');
subject.fileTest('path/fileExists','pathContent/file2');
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":"text content 2"}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file2":""}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":"text content 2"}});
	subject.fileTest('path/fileExists','pathContent/file2');
mock.restore();
subject.normalize(faker.phone.phoneNumberFormat());
subject.normalize(faker.phone.phoneNumberFormat());
subject.normalize('212-867-756');
subject.format(faker.phone.phoneNumberFormat(),'',"defined");
subject.format(faker.phone.phoneNumberFormat(),'',"defined");
subject.format('212-867-756','',"defined");
subject.format('212-867-756','',"defined");
subject.format('212-867-756','',{"normalize": true});
subject.blackListNumber(faker.phone.phoneNumberFormat());
subject.blackListNumber(faker.phone.phoneNumberFormat());
subject.blackListNumber('212-867-756');
